apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-build-ci
spec:
  containers:
    - name: maven
      image: maven:3.9-eclipse-temurin-17 # More robust multi-arch support
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/
    - name: docker-tools
      image: docker:dind # Standard Docker-in-Docker image (Multi-arch)
      command: ["cat"]
      tty: true
      volumeMounts:
        - mountPath: /var/run
          name: docker-sock
    - name: trufflehog
      image: trufflesecurity/trufflehog:latest # Official multi-arch image
      command: ["cat"]
      tty: true
    - name: licensefinder
      image: vishwakftw/license_finder:latest # Verify if an ARM version exists or rebuild
      command: ["cat"]
      tty: true
  volumes:
    - name: m2
      hostPath:
        path: /tmp/.m2/
    - name: docker-sock
      hostPath:
        path: /var/run
    - name: trivycache
      hostPath:
        path: /tmp/trivycache/
