apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-build-ci
spec:
  containers:
    - name: maven
      [cite_start]image: maven:3.9-eclipse-temurin-17 # Supported on ARM/AMD64 [cite: 1]
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/
    - name: docker-tools
      [cite_start]image: docker:dind # Fixes "exec format error" 
      command: ["cat"]
      tty: true
      volumeMounts:
        - mountPath: /var/run
          name: docker-sock
    - name: trufflehog
      [cite_start]image: trufflesecurity/trufflehog:latest # Official multi-arch image 
      command: ["cat"]
      tty: true
    - name: licensefinder
      image: licensefinder/license_finder:latest # Fixes "ErrImagePull"
      command: ["cat"]
      tty: true
  volumes:
    - name: m2
      hostPath:
        path: /tmp/.m2/
    - name: docker-sock
      hostPath:
        path: /var/run
    - name: trivycache
      hostPath:
        path: /tmp/trivycache/
